[package]
name = "mini-redis-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "client",
    "server",
]

[dev-dependencies]
tokio = { version = "1.32.0", features = ["full"] }
client = { path = "./client" }
server = { path = "./server" }
tempdir = "0.3.7"

